# Generated by Django 5.2.4 on 2025-08-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
