# Generated by Django 5.2.4 on 2025-08-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_tweet_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description (optional)', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='title',
            field=models.CharField(default=0, help_text='A catchy title for your post', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.TextField(help_text='Main content of your post', max_length=280),
        ),
    ]
